<a href="https://colab.research.google.com/github/edwardcalvinvazc-maker/MLSamples/blob/main/numpy_lib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
arr_1d = np.array([1,2,3,4,5,6])
arr_1d

array([1, 2, 3, 4, 5, 6])

In [3]:
arr_2d = np.array([[1,2,3],[5,6,7]])
arr_2d

array([[1, 2, 3],
       [5, 6, 7]])

In [14]:
arr_3d = ([[1, 2], [3, 4]], [[5, 6], [7, 8]])
arr_3d

([[1, 2], [3, 4]], [[5, 6], [7, 8]])

In [20]:
zero = np.zeros((4,4))
zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
ones = np.ones((4,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
re_shape = arr_1d.reshape(2,3)
re_shape

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
a = ([1,2],[3,4])
b = ([5,6],[7,8])
dot_pro = np.dot (a,b)
dot_pro

array([[19, 22],
       [43, 50]])

In [40]:
a = np.random.randint(20,170,100)
mean_of_a = np.mean(a)
mean_of_a

np.float64(92.88)

In [41]:
median_of_a = np.median(a)
median_of_a

np.float64(93.5)

In [42]:
Sd = np.std(a)
Sd

np.float64(43.80348844555648)

In [43]:
Var = np.var(a)
Var

np.float64(1918.7456000000002)

In [44]:
sum = np.sum(a)
sum

np.int64(9288)

In [46]:
cumulative_sum = np.cumsum(a)
cumulative_sum

array([ 133,  294,  318,  465,  506,  581,  671,  758,  884,  950, 1046,
       1097, 1124, 1177, 1286, 1314, 1458, 1623, 1731, 1794, 1932, 2039,
       2073, 2112, 2164, 2207, 2341, 2405, 2476, 2525, 2651, 2744, 2780,
       2805, 2883, 2906, 2983, 3112, 3180, 3291, 3413, 3471, 3610, 3632,
       3660, 3791, 3940, 4101, 4239, 4380, 4438, 4549, 4664, 4811, 4979,
       5042, 5174, 5268, 5413, 5468, 5508, 5584, 5660, 5744, 5879, 6002,
       6097, 6257, 6325, 6354, 6439, 6473, 6609, 6652, 6771, 6841, 6972,
       7098, 7184, 7209, 7251, 7378, 7483, 7651, 7772, 7817, 7959, 8021,
       8118, 8285, 8439, 8488, 8584, 8615, 8724, 8797, 8957, 9072, 9229,
       9288])

In [48]:
a = ([1,2],[3,4])
b = ([5,6],[7,8])
inv = np.linalg.inv(a)
inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [49]:
derterminant = np.linalg.det(b)
derterminant

np.float64(-2.000000000000005)

In [50]:
random = np.random.rand(3,3)
random

array([[0.38180995, 0.95140522, 0.39679889],
       [0.2011582 , 0.08573174, 0.47313221],
       [0.56063467, 0.2782048 , 0.06128666]])

In [52]:
random_normal = np.random.randn(3,3)
random_normal

array([[ 0.49148559,  0.6509054 , -0.02015311],
       [-0.57760504,  1.27719438,  0.73404909],
       [ 0.76307825, -0.28976603,  0.29323014]])

In [55]:
max_value = np.max(cumulative_sum)
max_value

np.int64(9288)

In [56]:
min_value = np.min(cumulative_sum)
min_value

np.int64(133)

In [57]:
indx_max_value = np.argmax(cumulative_sum)
indx_max_value

np.int64(99)

In [58]:
indx_min_value = np.argmin(cumulative_sum)
indx_min_value

np.int64(0)

In [60]:
label = np.where(random_normal > 0, '+' , '-')
label

array([['+', '+', '-'],
       ['-', '+', '+'],
       ['+', '-', '+']], dtype='<U1')

In [62]:
combine = np.concatenate(arr_2d)
combine

array([1, 2, 3, 5, 6, 7])

In [63]:
no_50 = np.linspace(0,50,20)
no_50

array([ 0.        ,  2.63157895,  5.26315789,  7.89473684, 10.52631579,
       13.15789474, 15.78947368, 18.42105263, 21.05263158, 23.68421053,
       26.31578947, 28.94736842, 31.57894737, 34.21052632, 36.84210526,
       39.47368421, 42.10526316, 44.73684211, 47.36842105, 50.        ])

In [65]:
numbers_bw_30 = np.arange(0,30,3)
numbers_bw_30

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [68]:
r = ([1,2,2,5,4,6,6,5,9,8,8,0,9,])
r_uni = np.unique(r)
r_uni

array([0, 1, 2, 4, 5, 6, 8, 9])

In [69]:
transpose = np.transpose(a)
transpose

array([[1, 3],
       [2, 4]])